/*
CSCI 466
Group Project
Spring 2022
*/

DROP TABLE INVENTORY;
DROP TABLE USER;
DROP TABLE EMPLOYEES;
DROP TABLE ORDERS;

/*
TABLE INITIALIZATION
*/

CREATE TABLE INVENTORY(
    PRODUCTID       INT         NOT NULL    AUTO_INCREMENT,
    PRODUCTNAME     CHAR(20)    NOT NULL,
    QUANTITY        INT         NOT NULL,
    PRICE           INT         NOT NULL,
    img             TEXT        NOT NULL,

    PRIMARY KEY (PRODUCTID)
);

CREATE TABLE USER(
    USERID          INT         NOT NULL    AUTO_INCREMENT,
    USERNAME        CHAR(20)    NOT NULL,
    PASSPHRASE      CHAR(20)    NOT NULL,

    PRIMARY KEY (USERID)
);

CREATE TABLE EMPLOYEES(
    EMPID           INT         NOT NULL    AUTO_INCREMENT,
    EMPNAME         CHAR(20)    NOT NULL,
    PASSPHRASE      CHAR(20)    NOT NULL,
    
    PRIMARY KEY (EMPID)
);

CREATE TABLE ORDERS(
    TRACKINGID      INT         NOT NULL    AUTO_INCREMENT,
    PHONE           CHAR(10)    NOT NULL,
    FULLNAME        CHAR(30)    NOT NULL,
    CREDITCARD      CHAR(9)     NOT NULL,
    ADDRESS         CHAR(50)    NOT NULL,
    STATUS          CHAR(10)    NOT NULL,

    PRIMARY KEY (TRACKINGID)
);
