/*
SAMPLE TABLES
*/

INSERT INTO INVENTORY
    (PRODUCTNAME,QUANTITY,PRICE)
    VALUES('TELEVISION', '500', '1000');

INSERT INTO INVENTORY
    (PRODUCTNAME,QUANTITY,PRICE)
    VALUES('IPHONE', '250', '750');

INSERT INTO INVENTORY
    (PRODUCTNAME,QUANTITY,PRICE)
    VALUES('LAPTOP', '250', '1500');

INSERT INTO INVENTORY
    (PRODUCTNAME,QUANTITY,PRICE)
    VALUES('HELMET', '100', '50');

INSERT INTO INVENTORY
    (PRODUCTNAME,QUANTITY,PRICE)
    VALUES('CHARGER', '1000', '15');

INSERT INTO INVENTORY
    (PRODUCTNAME,QUANTITY,PRICE)
    VALUES('CANDLE', '150', '10');

INSERT INTO INVENTORY
    (PRODUCTNAME,QUANTITY,PRICE)
    VALUES('PILLOW', '300', '25');

INSERT INTO INVENTORY
    (PRODUCTNAME,QUANTITY,PRICE)
    VALUES('GUITAR', '100', '100');

INSERT INTO INVENTORY
    (PRODUCTNAME,QUANTITY,PRICE)
    VALUES('PURSE', '275', '50');

INSERT INTO INVENTORY
    (PRODUCTNAME,QUANTITY,PRICE)
    VALUES('SHIRT', '500', '15');

INSERT INTO INVENTORY
    (PRODUCTNAME,QUANTITY,PRICE)
    VALUES('PANTS', '500', '25');

INSERT INTO INVENTORY
    (PRODUCTNAME,QUANTITY,PRICE)
    VALUES('SOCKS', '250', '10');

INSERT INTO INVENTORY
    (PRODUCTNAME,QUANTITY,PRICE)
    VALUES('HAT', '100', '20');

INSERT INTO INVENTORY
    (PRODUCTNAME,QUANTITY,PRICE)
    VALUES('JACKET', '75', '50');

INSERT INTO INVENTORY
    (PRODUCTNAME,QUANTITY,PRICE)
    VALUES('GUCCI', '5', '2500');

INSERT INTO INVENTORY
    (PRODUCTNAME,QUANTITY,PRICE)
    VALUES('HEADPHONES', '250', '50');

INSERT INTO INVENTORY
    (PRODUCTNAME,QUANTITY,PRICE)
    VALUES('MOUSE', '300', '40');

INSERT INTO INVENTORY
    (PRODUCTNAME,QUANTITY,PRICE)
    VALUES('KEYBOARD', '400', '35');

INSERT INTO INVENTORY
    (PRODUCTNAME,QUANTITY,PRICE)
    VALUES('MONITOR', '1000', '300');

INSERT INTO INVENTORY
    (PRODUCTNAME,QUANTITY,PRICE)
    VALUES('DESK', '175', '150');

INSERT INTO EMPLOYEES
    (EMPNAME,PASSPHRASE)
    VALUES('OWNER','ADMIN');
    
INSERT INTO EMPLOYEES
    (EMPNAME,PASSPHRASE)
    VALUES('MANAGER','ADMIN123');

INSERT INTO USER
    (USERNAME,PASSPHRASE)
    VALUES('DANIEL123','SECUREPASSWORD123');

INSERT INTO USER
    (USERNAME,PASSPHRASE)
    VALUES('DISHA456','SAMPLEPASSWORD123');

INSERT INTO USER
    (USERNAME,PASSPHRASE)
    VALUES('KALPIT789','BADPASSWORD123');

INSERT INTO USER
    (USERNAME,PASSPHRASE)
    VALUES('ASHISH012','HACKABLEPASSWORD123');

INSERT INTO USER
    (USERNAME,PASSPHRASE)
    VALUES('DEV345','SOMEPASSWORD123');

INSERT INTO ORDERS
    (PHONE,FULLNAME,CREDITCARD,ADDRESS,STATUS)
    VALUES('6302896700','DANIEL BENDIK','123456789','123 SAMPLE STREET','Processing');
    
INSERT INTO ORDERS
    (PHONE,FULLNAME,CREDITCARD,ADDRESS,STATUS)
    VALUES('8475778801','DISHA PATEL','987654321','321 HACKER LANE','Processing');
    
INSERT INTO ORDERS
    (PHONE,FULLNAME,CREDITCARD,ADDRESS,STATUS)
    VALUES('6308336212','KALPIT AMIN','111222333','987 CODE STREET','Processing');
    
INSERT INTO ORDERS
    (PHONE,FULLNAME,CREDITCARD,ADDRESS,STATUS)
    VALUES('8154557463','ASHISH PATEL','333222111','789 WHITE AVENUE','Shipped');
    
INSERT INTO ORDERS
    (PHONE,FULLNAME,CREDITCARD,ADDRESS,STATUS)
    VALUES('7083431224','DEV PATEL','123123123','100 RODEO DRIVE','Fulfilled');
